build_script:
  - cmd: build.cmd
version: '1.0.{build}'
assembly_info:
  patch: true
  file: src/AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-rc1'