version: '1.0.{build}'
skip_non_tags: true
build_script:
  - cmd: build.cmd Release
artifacts:
  - path: 'deploy/*.nupkg'
    name: FsDynamics
assembly_info:
  patch: true
  file: AssemblyInfo.fs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'